---
- name: Install required packages
  yum:
    state: present
    validate_certs: no
    disable_gpg_check: yes
    name:
    - openldap
#    - openldap-servers
    - openldap-clients
#    - python-ldap
    - python3-ldap3

